### ISSUE TITLE
InteractiveTextBox

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#1]
- The text is created offset from where my mouse is clicked (more than a whole cursor length, very noticable)
- Starting bounding box is shorter than actual Text
- Upon first selection the word "Box" blinks
- If delete everything in textbox, the bounding box shrinks then grows. When attempting to type afterwards text does not appear at first until wrapping occurs.

**Comment by maddoxamei** [comment]
"Box" no longer blinks, but the top row shifts as the cursor blinks

**Comment by blakeearth** [comment]
On the first bullet: are you talking about when objects are created, or when text is being typed?

**Comment by maddoxamei** [comment]
Splitting into separate issues
