### ISSUE TITLE
Present-Mode

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#11]
**Describe the bug**
Can't switch between slides in present mode

**Expected behavior**
Slide or animation to play when using arrow keys or mouse clicks

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Comment by hchasens** [comment]
I've added buttons, mouse clicks is a good idea but might cause problems with links and video

**Comment by hchasens** [comment]
I'm gonna close this as we have a solution, buttons, but we won't add clicking as it will interfere with video and links. Maybe we can reopen this if everything else is done.
