### ISSUE TITLE
Interactive-TextBox

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#12]
**Description**
Words "disappear" when delete sample text until a certain number are typed

**Replicate**
1. Create text-box
2. Select-Textbox
3. Delete All Sample Text
4. Type in characters

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Comment by blakeearth** [comment]
Fixed with 1cb7d73db5bcd459b818f80976f124c4662fb0ba
