### ISSUE TITLE
Interactive Textbox

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#13]
**Description**
Weird SelectionBox changes which makes typing hard

**Replicate**
1. Create text-box
2. Select-Textbox
3. Hold 'Backspace' until all letters are deleted

**Expected**
Empty textbox with some height still there. 

**Result**
Empty textbox with some height still there but displays text a whole line behind (one line is always not visible)

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Comment by blakeearth** [comment]
Fixed with 1cb7d73db5bcd459b818f80976f124c4662fb0ba
