### ISSUE TITLE
Annimations

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#14]
**Describe the bug**
Nothing happens if I select any annimation button

**To Reproduce**
1. Create Object
2. Select Object
3. Select Annimation

**Expected behavior**
Some visual indication a successful Annimation was created or is linked to an object

**Additional context**
Doesn't play during present mode (not sure if because not created or not work)

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Comment by hchasens** [comment]
I don't know if a visual indicator is set up yet.

**Comment by maddoxamei** [comment]
They successfully play now, still no indicator. Will close this and open a new issue for just indicator.
