### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#16]
**Describe the bug**
Throws error if not explicitly specify extension (some users might not know diff between them)

**To Reproduce**
1. Click Export
2. Type in name with no provided Extension
3. See error

**Expected behavior**
Export all slides to pngs

**Screenshots**
![image](https://user-images.githubusercontent.com/30241260/75628977-08e5c580-5bac-11ea-8fc7-d8a77e9233fc.png)

**Additional context**
Previously auto-specified .png if no extension provided?

**Comment by blakeearth** [comment]
This is the same issue as the one I just fixed with `.polly`. I'll fix it.

**Comment by blakeearth** [comment]
Fixed with 35f81b94a3d5e5706c043b7c8f235903c32e40ea
