### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#17]
**Describe the bug**
Tons of Errors

**To Reproduce**
1. Run bat
2. Click Save
3. See Warning
4. Type in new Name to save under

**Expected behavior**
Slides saved as serialized object

**Screenshots**
![image](https://user-images.githubusercontent.com/30241260/75629088-06d03680-5bad-11ea-92b2-150a3f126072.png)
![image](https://user-images.githubusercontent.com/30241260/75629090-12236200-5bad-11ea-8279-770845fea3b0.png)

**Additional context**
DOES NOT ERROR when overwriting previous save-data (i.e. used PollyPaint to create save data then saved under the same name but using LearningMyFriend)

**Comment by blakeearth** [comment]
@maddoxamei, were you saving with a `.polly` extension? It seems like when I tried to trim the `.` from the extension, the `.` in your username was chosen as the last one. It might be worth looking at an external library for this. In the meantime, I'm going to append `.polly` to filenames if they don't already have them.

**Comment by blakeearth** [comment]
I'm not totally sure if that's what you were doing, but in either case, this should resolve it: f70cce02d2381b585c4714e2be1bb855beb9cdae. Let me know if the problem still occurs.
