### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#18]
**Describe the bug**
Export triggers only the export of current slide

**Expected behavior**
Export export all slides, not just the current one

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Comment by blakeearth** [comment]
Fixed with 5017c9fbe57b4be61467b816b0190b041ec92983 (please note @yoyou446, you should stop passing `.png` as now export takes only a directory. The older version will still work)

**Comment by hchasens** [comment]
It's done

**Comment by blakeearth** [comment]
Thanks!
