### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#2]
- Selection as the default would be nice, it honestly took a bit to find the selection tool
- Having a new major menu field highlighted but still doing the previous selected tool is a bit confusing. Maybe everytime a new major menu field is selected without selecting a minor tool, defaultly go back to selection?

**Comment by maddoxamei** [comment]
It'd be nice to have the initial text in the InteractiveTextBox disappearwhen start typing or not not appear at all in the start but auto-select it so I can start typing immediately!

Also not having the text constantly shifting while the cursor blinks would be nice too :)

**Comment by maddoxamei** [comment]
It'd also be nice to have a tool for creating bullet points under the text field that way I don't have to remember or keep looking up the shortcut to enable/create them

**Comment by yoyou446** [comment]
> * Selection as the default would be nice, it honestly took a bit to find the selection tool
> * Having a new major menu field highlighted but still doing the previous selected tool is a bit confusing. Maybe everytime a new major menu field is selected without selecting a minor tool, defaultly go back to selection?

**Comment by blakeearth** [comment]
I solved line breaks in the middle of words with a ' ' NARROW NO-BREAK SPACE. Text shifting still happens, but it is much less noticeable.

**Comment by maddoxamei** [comment]
Splitting into separate issues
