### ISSUE TITLE
Move Up

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#22]
**Describe the bug**
Slide is not changing position

**To Reproduce**
1. Create Shape
2. Click on New
3. Click on Up

**Expected behavior**
Current slide to move up in the queue

**Additional Information**
Moving the slide down works

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](dde12734fda0c40a528869c8002d6dea52a206e9)

**Comment by hchasens** [comment]
I did some tests and I am calling `Window.moveSlideUp();` Its not a frontend problem I don't think.

**Comment by blakeearth** [comment]
Fixed with 405b38b89a749cbd5d9495dd04bd9aa9f1ed3b72
