### ISSUE TITLE
Unable Delete First Slide

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#23]
**Describe the bug**
Unable to delete first slide, even if have multiple slides created

**To Reproduce**
1. Create shape
2. Click New
3. Click on the first slide to go back to it
4. Click delete

**Expected behavior**
First slide is deleted

**Additional context**
Besides the first slide, all other slides can be successfully deleted in any order

**Comment by maddoxamei** [comment]
It actually causes an error to be thrown and crash the program

![image](https://user-images.githubusercontent.com/30241260/75631184-aa761280-5bbe-11ea-89e6-67c874e09c9e.png)

**Comment by blakeearth** [comment]
Fixed with 405b38b89a749cbd5d9495dd04bd9aa9f1ed3b72 (along with upward swapping)
