### ISSUE TITLE
Animation and PresentMode

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#24]
**Describe the bug**
Slides with Animations have their thumbnails changed to match the end frame during present mode after exiting present mode

**To Reproduce**
1. Create shape with translate annimation
2. Click present
3. go through all annimations/slides (auto-exits)

**Expected behavior**
Thumbnail and editable slide look the same

**Screenshots**
![image](https://user-images.githubusercontent.com/30241260/75631324-d5149b00-5bbf-11ea-8a86-10474faeb78b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](dde12734fda0c40a528869c8002d6dea52a206e9)

**Comment by blakeearth** [comment]
Fixed with abd387af0ccdb1b35319d2dfd627a2e7e28dc547
