### ISSUE TITLE
Annimations

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#25]
**Description**
Confusion over if animation successfully added or where it's going to go and what any added animations already are

**To Reproduce**
1. Create Object
2.    Select Object
3.    Select Annimation

**Expected behavior**
Some visual indication a successful Annimation was created or is linked to an object

**Snapshots with Context**

Please guess the annimations attached to the object

![image](https://user-images.githubusercontent.com/30241260/75631475-35580c80-5bc1-11ea-8539-b9c7986d2f83.png)

**Comment by blakeearth** [comment]
Fixed with fe2659f1bd7449927c8ba15385d35e6985675ad0
