### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#3]
Copied+Pasted free-drawn objects are not persisting through saves
Annimate throws error
Present throws error
Imported image has weird panning, bounding box does not follow correctly

**Comment by blakeearth** [comment]
Fixed issue with FreeDraw in 3d7a193f3e895e5966488fd1a2b5e840817f718c

**Comment by blakeearth** [comment]
Do you know what error present was throwing?

**Comment by blakeearth** [comment]
Fixed issue with images in 0f3d85091c741485a4a68922cb36e61db62f6179
