### ISSUE TITLE
Scroll Toolbar

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#5]
**Describe the issue**
Went to go add a slide and accidentally deleted my current slide instead

**To Reproduce**
I used print statements to test, will not upload

**Screenshots**
![image](https://user-images.githubusercontent.com/30241260/75627693-62e08e00-5ba0-11ea-9403-1be6dc91ca8e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Additional context**
Please separate the add/delete slide buttons

**Comment by hchasens** [comment]
This has been done
