### ISSUE TITLE
Scrolling not working

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#7]
**Describe the bug**
The scrollbar doesn't scroll the thumbnails

**To Reproduce**
1. Create multiple slides
2. Click and drag the scroll bar up to the top

**Expected behavior**
The thumbnails be scrolled up to the last slide

**Screenshots**
![image](https://user-images.githubusercontent.com/30241260/75627803-89eb8f80-5ba1-11ea-8461-7a4a3d39cdb9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Comment by hchasens** [comment]
I've not linked it yet.

**Comment by hchasens** [comment]
its done
