### ISSUE TITLE
Present Mode

### ISSUE THREAD

**Issue by maddoxamei** [Software-Engineering-Spring-2020/Learning-My-Friend#9]
**Expected behavior**
Toolbars to disappear and have the the slides be displayed to the whole window-size 

**Screenshots**
![image](https://user-images.githubusercontent.com/30241260/75628484-5b70b300-5ba7-11ea-8d1f-4c3e60e6e654.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Last Pull: [[SHA]](d4689fee955607cd1dbf07b99c3a2d6f92a1cb05)

**Comment by hchasens** [comment]
Well the toolbars to disappear

**Comment by blakeearth** [comment]
Fixed with 6a777861b84bf2953eda38ed0de21fe1833f7c4a
